---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: concourse
  namespace: office
...

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: concourse-office-admin
  namespace: office

subjects:
  - kind: ServiceAccount
    name: concourse
    namespace: office

roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
...
